### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lapplislazuli** [Twonki/PollyPuncher#1]
Initial Set 

- [x] Safe 2 File
- [x] Re-Load Last Key 
- [x] Show whether Key is set / Warning 
- [x] Delete Temp File on Close 
- [x] Sampling Rate per Sampler
- [x] Figure out all Standard Voices
- [x] Volume Adjustment working 
- [x] Layout / Look 
- [x] Tooltips of Elements
- [x] No crash on Doubleclick - handling of restart plays when device is in use?

Nice 2 Have 

- [x] Fire by Hotkey / Set Hotkey
- [ ] History of last files / reuse of files

**Comment by lapplislazuli** [comment]
Oky doke, initial version is ok
